### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by johhansantana** [Utzel-Butzel/react-virtual-keyboard#2]
what npm package do I need to install in order to use this component?

**Comment by Utzel-Butzel** [comment]
Hi jsantana90, `npm install` inside the folder should do the job. Then you can import it via `import Keyboard from 'Keyboard';` into your react application

**Comment by clamstew** [comment]
Can you run `npm publish` for this repo so we can use yarn and npm to install with `npm install react-virtual-keyboard --save` or `yarn add react-virtual-keyboard`, instead of cloning and running `npm install` in the folder?

The namespace is open - https://www.npmjs.com/package/react-virtual-keyboard.

**Comment by Utzel-Butzel** [comment]
Hi clamstew, I have published the package as an npm-package: https://www.npmjs.com/package/react-virtual-keyboard

**Comment by clamstew** [comment]
Thanks!
